# Generated by Django 4.2.5 on 2025-03-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_alter_bookingslot_date_alter_bookingslot_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='password',
        ),
    ]
